"""Conditions générales imprimées au verso de la booking note NEWTOWT.

Texte **contractuel**, repris verbatim du gabarit Word fourni par la direction
(``Booking_note_vierge``, trame de type BIMCO CONLINEBOOKING). Il est conservé
ici comme donnée versionnée plutôt que dans le code du générateur : une clause
se relit, se date et se compare d'une version à l'autre — c'est ce que permet un
fichier dédié, pas une chaîne noyée dans une fonction de mise en page.

⚠️ **Ne pas reformuler.** Toute correction de fond (numérotation, renvoi,
juridiction, plafond de responsabilité) engage la responsabilité du transporteur
et doit être validée par la direction, pas ajustée au fil d'une refonte
technique. Les clauses 3, 4, 11, 13 et 16 conditionnent la couverture P&I.

La clause 22 (ANEMOS) est propre à NEWTOWT : elle décrit le label de transport
vélique et ne figure dans aucun gabarit BIMCO.
"""

from __future__ import annotations

BOOKING_NOTE_TERMS_TITLE = "FULL TERMS OF THE CARRIER\u2019S BILL OF LADING FORM"

# Chaque entrée est un paragraphe. Les intitulés de clause (« 1.Definition. »)
# sont des paragraphes à part entière, comme dans le gabarit d'origine.
BOOKING_NOTE_TERMS: tuple[str, ...] = (
    "1.Definition.",
    '"Merchant" includes the shipper, the receiver, the consignor, the consignee, the holder of the Bill of Lading, the owner of the cargo and any person entitled to possession of the cargo.',
    "2. Notification.",
    "Any mention in this Bill of Lading of parties to be notified of the arrival of the cargo is solely for the information of the Carrier and failure to give such notification shall not involve the Carrier in any liability nor relieve the Merchant of any obligation hereunder.",
    "3. Liability for Carriage Between Port of Loading and Port of Discharge.",
    '(a)The International Convention for the Unification of Certain Rules of Law relating to Bills of Lading signed at Brussels on 25 August 1924 ("the Hague Rules") as amended by the Protocol signed at Brussels on 23 February 1968 ("the Hague-Visby Rules") and as enacted in the country of shipment shall apply to this Contract. When the Hague-Visby Rules are not enacted in the country of shipment, the corresponding legislation of the country of destination shall apply, irrespective of whether such legislation may only regulate outbound shipments.',
    "When there is no enactment of the Hague-Visby Rules in either the country of shipment or in the country of destination, the Hague-Visby Rules shall apply to this Contract save where the Hague Rules as enacted in the country of shipment or, if no such enactment is in place, the Hague Rules as enacted in the country of destination apply compulsorily to this Contract.",
    'The Protocol signed at Brussels on 21 December 1979 ("the SDR Protocol 1979") shall apply where the Hague-Visby Rules apply, whether mandatorily or by this Contract.',
    "The Carrier shall in no case be responsible for loss of or damage to cargo arising prior to loading, after discharging, or with respect to deck cargo and live animals.",
    "(b)If the Carrier is held liable in respect of delay, consequential loss or damage other than loss of or damage to the cargo, the liability of the Carrier shall be limited to the freight for the carriage covered by this Bill of Lading, or to the limitation amount as determined in sub-clause 3(a), whichever is the lesser.",
    "(c)The aggregate liability of the Carrier and/or any of its servants, agents or independent contractors under this Contract shall, in no circumstances, exceed the limits of liability for the total loss of the cargo under sub-clause 3(a) or, if applicable, the Additional Clause.",
    "4. Law and Jurisdiction.",
    "(a)Disputes arising out of or in connection with this Bill of Lading shall be governed by French law.",
    "(b)The Tribunal de Commerce de Paris (France) will have exclusive jurisdiction over any dispute arising from this Bill of Lading, including in case of multiple defendants and in case of claims against third parties, notwithstanding any contrary provision appearing in any other documents of the Parties.",
    "5. The Scope of Carriage.",
    "The intended carriage shall not be limited to the direct route but shall be deemed to include any proceeding or returning to or stopping or slowing down at or off any ports or places for any reasonable purpose connected with the carriage including bunkering, loading, discharging, or other cargo operations and maintenance of Vessel and crew.",
    "6. Substitution of Vessel.",
    "The Carrier shall be at liberty to carry the cargo or part thereof to the Port of discharge by the said or other vessel or vessels either belonging to the Carrier or others, or by other means of transport, proceeding either directly or indirectly to such port.",
    "7. Transhipment.",
    "The Carrier shall be at liberty to tranship, lighter, land and store the cargo either on shore or afloat and reship and forward the same to the Port of discharge.",
    "8. Liability for Pre- and On-Carriage.",
    "When the Carrier arranges pre-carriage of the cargo from a place other than the Vessel's Port of loading or on-carriage of the cargo to a place other than the Vessel's Port of discharge, the Carrier shall contract as the Merchant's Agent only and the Carrier shall not be liable for any loss or damage arising during any part of the carriage other than between the Port of loading and the Port of discharge even though the freight for the whole carriage has been collected by him.",
    "9. Loading and Discharging.",
    "(a) The Goods shall be brought into the holds, loaded, stowed and/or trimmed, tallied, lashed and/or secured and taken from the holds and discharged by the Merchant, free of any risk, liability and expense whatsoever to the Carrier. The Merchant shall provide and lay all dunnage material as required for the proper stowage and protection of the cargo on board, the Carrier allowing the use of all dunnage available on board. The Merchant shall be responsible for and pay the cost of removing their dunnage after discharge of the Goods under this Bill of Lading and time to count until dunnage has been removed.",
    "(b) the Carrier shall provide free use of the Vessel's cargo-handling gear and sufficient motive power to operate the same. Unless caused or contributed to by negligence or lack of skill of the Merchant’ servants, agents or subcontractors, time actually lost by breakdown of the Vessel's cargo-handling gear or lack of sufficient power shall not count as laytime or time on demurrage. The Carrier shall provide free use of lighting as on board.",
    "(c) The Merchant shall be responsible for damage (fair wear and tear excepted) to any part of the Vessel caused by Stevedores. The Merchant shall be liable for all costs for repairing such damage and for any time lost, which shall be paid in an amount equivalent to the demurrage rate.",
    "(d) The Master or the Carrier shall notify the Merchant or their agents and the Stevedores of any damage as soon as reasonably possible, failing which the Merchant shall not be responsible.",
    "(e) Stevedore damage affecting seaworthiness shall be repaired without any delay before the Vessel sails from the port where such damage was caused or discovered. Stevedore damage affecting the Vessel’s trading capabilities shall be repaired before leaving the last port of discharge, failing which the Merchant shall be liable for resulting losses. All other damage which is not repaired before leaving the last port of discharge shall be repaired by the Carrier and settled by the Merchant on receipt of Carrier’s supported invoice.",
    "(f) The Merchant shall accept its reasonable proportion of unidentified loose cargo.",
    "10. Laytime",
    "(a) The cargo shall be loaded and discharged within a total running 6 hours (for an equivalent of 1000 metric tonnes) weather permitting, Sundays and holidays excepted, unless used, in which event time used shall count.",
    "(c) Commencement of laytime (loading and discharging) Laytime for loading and discharging shall commence at 13.00 hours, if Notice of Readiness is given up to and including 12.00 hours, and at 06.00 hours next working day if notice given during office hours after 12.00 hours. Notice of readiness at loading port to be given to the Merchant or their agents. Notice of readiness at the discharging port to be given to the Merchant or their agents.",
    "(d) If the loading/discharging berth is not available on the Vessel's arrival at or off the port of loading/discharging, the Vessel shall be entitled to give notice of readiness within ordinary office hours on arrival. Laytime or time on demurrage shall then count as if she were in berth and in all respects ready for loading/discharging provided that the Master warrants that she is in fact ready in all respects. Time used in moving from the place of waiting to the loading/ discharging berth shall not count as laytime. If, after inspection, the Vessel is found not to be ready in all respects to load/discharge time lost after the discovery thereof until the Vessel is again ready to load/discharge shall not count as laytime. Time used before commencement of laytime shall count.",
    "11. Demurrage",
    "Demurrage at the loading and discharging port is payable by the Merchant at the rate of EUR 50 per tonne per day or pro rata for any part of a day. Demurrage shall fall due day by day and shall be payable by the Merchant upon receipt of the Carrier's invoice.",
    "12. Freight, Charges, Costs, Expenses, Duties, Taxes and Fines.",
    "Freight is deemed earned, non-discountable, non-returnable, on shipment and Cargo and/or Vessel lost or not lost.",
    "Unless otherwise specified, freight and/or charges under this Contract are payable by the Merchant to the Carrier on demand. Interest at Libor (or its successor) plus 2 per cent. shall run from fourteen days after the date when freight and charges are payable.",
    "The Merchant shall be liable for all costs and expenses of fumigation, gathering and sorting loose cargo and weighing onboard, repairing damage to and replacing packing due to excepted causes, and any extra handling of the cargo for any of the aforementioned reasons.",
    "The Merchant shall be liable for any dues, duties, taxes and charges which under any denomination may be levied, inter alia, on the basis of freight, weight of cargo or tonnage of the Vessel.",
    "The Merchant shall be liable for all fines, penalties, costs, expenses and losses which the Carrier, Vessel or cargo may incur through nonobservance of Customs House and/or import or export regulations.",
    "The Carrier is entitled in case of incorrect declaration of contents, weights, measurements or value of the cargo to claim double the amount of freight which would have been due if such declaration had been correctly given. For the purpose of ascertaining the actual facts, the Carrier shall have the right to obtain from the Merchant the original invoice and to have the cargo inspected and its contents, weight, measurement or value verified.",
    "13. Lien.",
    "(a) The Carrier shall have a lien on the cargo and on all sub-freights payable in respect of the cargo for freight, deadfreight, demurrage, claims for damages and for all other amounts due under this Bill of Lading and all costs of recovering same, including legal costs.",
    "(b) Without prejudice to subclause (a) above, if upon the Vessel’s arrival at or off a port or place of discharge any freight then due and payable has not been received by the Carrier, the Carrier shall be entitled to hold the Vessel at a safe place outside or inside territorial waters until such payment has been received in full, and any resulting loss of time shall be compensated by the Carrier. The Merchant shall reimburse the Carrier for the cost of any deviation insurance, and shall indemnify the Carrier against any claim raised by any third party (including the costs of defending the same), and promptly provide appropriate security or substitute security to obtain the Vessel’s unimpeded departure in the event of its actual or threatened arrest or detention.",
    "14. General Average and Salvage.",
    "General Average shall be adjusted, stated and settled in Paris according to the York-Antwerp Rules 2016, in respect of all cargo, whether carried on or under deck. In the event of accident, danger, damage or disaster before or after commencement of the carriage resulting from any cause whatsoever, whether due to negligence or not, for which or for the consequence of which the Carrier is not responsible by statute, contract or otherwise, the Merchant shall contribute with the Carrier in General Average to the payment of any sacrifice, losses or expenses of a General Average nature that may be made or incurred, and shall pay salvage and special charges incurred in respect of the cargo. If a salving vessel is owned or operated by the Carrier, salvage shall be paid for as fully as if the salving vessel or vessels belonged to strangers.",
    "15. Both-to-Blame Collision Clause.",
    "If the Vessel comes into collision with another vessel as a result of the negligence of the other vessel and any act, negligence or default of the Master, Mariner, Pilot or the servants of the Carrier in the navigation or in the management of the Vessel, the Merchant will indemnify the Carrier against all loss or liability to the other or non-carrying vessel or her Owner in so far as such loss or liability represents loss of or damage to or any claim whatsoever of the owner of the cargo paid or payable by the other or non-carrying vessel or her Owner to the owner of the cargo and set-off, recouped or recovered by the other or non-carrying vessel or her Owner as part of its claim against the carrying vessel or Carrier. The foregoing provisions shall also apply where the Owner, operator or those in charge of any vessel or vessels or objects other than, or in addition to, the colliding vessels or objects are at fault in respect of a collision or contact.",
    "16. Laycan, ETA and Noon Position Notices, and Cancellation",
    "(a)The Merchant shall give Carrier a proposed Laycan of minimum fourteen (14) days (the “Proposed Laycan Period”) at the Loading Port minimum thirty (30) days prior to the first day of the proposed Laycan Period. The Merchant shall confirm to the Carrier the Proposed Laycan Period within maximum five (5) days of receipt of the Carrier’s Proposed Laycan Period or propose an Adjusted Laycan Period. If the Carrier fails to respond within five (5) days, the carrier’s Proposed Laycan Period shall be the Agreed Laycan. If the Carrier propose an Adjusted Laycan Period, provided that such Adjusted Laycan Period falls within a fourteen (14) day period both ends of the Merchant’s Proposed Laycan Period, the Adjusted Laycan Period shall become the Agreed Laycan.",
    "(b)The Carrier shall give the Merchant Estimated Time of Arrival notices (“ETA Notices”) at the Port of Loading and, after sailing from the Port of Loading, at the Port of Discharge, and Noon Position Notices (Latitude and Longitude position of the Vessel at 1200 UT) every day from the seventh (7th) day prior to the first day of the Agreed Laycan until completion of the carriage.",
    "(c)Should the Vessel not be ready to load (whether in berth or not) by the last day of the Agreed Laycan plus a free margin of 48 hours (the Cancelling Date”), the Merchant shall have the option of cancelling the carriage under this Bill of lading at no cost which shall be the Merchant’s sole and exclusive remedy for all and any losses flowing from the non-performed voyage.",
    "(d)Should the Cargo not be ready to be loaded on the Vessel within 72 hours of the Vessel’s tendering its Notice of Readiness, the Vessel shall have the option of sailing without the Cargo in which case the voyage shall be deemed performed and Freight fully payable as dead freight together with any accrued demurrage and any other sums due under the Bill of Lading for the relevant voyage.",
    "(e)Should the Carrier anticipate that despite the exercise of due diligence, the Vessel will not be ready to load by the Cancelling Date, they shall notify the Merchant thereof without delay stating the expected date of the Vessel’s readiness to load and asking whether the Merchant will exercise the option of cancelling the carriage, or agree to a new cancelling date. Such option must be declared by the Merchant within 48 hours of receipt of Carrier’s notice. If the Merchant do not exercise their option of cancelling, then this Bill of lading shall be deemed to be amended such that the fourteenth (14th) day after the new readiness date stated in Carrier’s notification to the Merchant shall be the new Cancelling Date.",
    "(f)Should the Merchant anticipate that despite the exercise of due diligence, the Cargo will not be ready to load by the Vessel’s ETA Notice, they shall notify the Carrier thereof without delay stating the expected date of the Cargo’s readiness to load and asking whether the Carrier will exercise the option of sailing without the cargo on board or will be prepared to wait until the expected Cargo’s readiness date. The Carrier shall always consider in good faith whether it is possible to accommodate the Merchant’s expected Cargo’s readiness date to the extent possible always without compromising the Vessel’s schedule and next carriages (which shall have priority) and always without prejudice to paragraph (e) above.",
    "17. Government directions, War, Epidemics, Ice, Strikes, etc.",
    "The Master and the Carrier shall have liberty to comply with any order or directions or recommendations in connection with the carriage under this contract given by any Government or Authority, or anybody acting or purporting to act on behalf of such Government or Authority, or having under the terms of the insurance on the Vessel the right to give such orders or directions or recommendations.",
    "Should it appear that the performance of the carriage would expose the Vessel or any cargo onboard to risk of seizure, damage or delay, in consequence of war, warlike operations, blockade, riots, civil",
    "commotions or piracy, or any person onboard to risk of loss of life or freedom, or that any such risk has increased, the Master may discharge the cargo at the Port of loading or any other safe and convenient port.",
    "Should it appear that epidemics; quarantine; ice; labour troubles, labour obstructions, strikes, lockouts (whether onboard or on shore); difficulties in loading or discharging would prevent the Vessel from leaving the Port of loading or reaching or entering the Port of discharge or there discharging in the usual manner and departing therefrom, all of which safely and without unreasonable delay, the Master may discharge the cargo at the Port of loading or any other safe and convenient port.",
    "The discharge, under the provisions of this Clause, of any cargo shall be deemed due fulfilment of the contract of carriage.",
    "If in connection with the exercise of any liberty under this Clause any extra expenses are incurred they shall be paid by the Merchant in addition to the freight, together with return freight, if any, and a reasonable compensation for any extra services rendered to the cargo.",
    "18.  Himalaya Clause",
    "(a) For the purposes of this contract, the term “Servant” shall include the owners, managers, and operators of vessels (other than the Carrier); underlying carriers; stevedores and terminal operators; and any direct or indirect servant, agent, or subcontractor (including their own subcontractors), or any other party employed by or on behalf of the Carrier, or whose services or equipment have been used to perform this contract whether in direct contractual privity with the Carrier or not.",
    "It is hereby expressly agreed that no Servant shall in any circumstances whatsoever be under any liability whatsoever to the Merchant or other party to this contract (hereinafter termed “Merchant”) for any loss, damage or delay of whatsoever kind arising or resulting directly or indirectly from any act, neglect or default on the Servant’s part while acting in the course of or in connection with the performance of this contract.",
    "Without prejudice to the generality of the foregoing provisions in this clause, every exemption, limitation, condition and liberty contained herein (other than Art III Rule 8 of the Hague/Hague-Visby Rules if incorporated herein) and every right, exemption from liability, defence and immunity of whatsoever nature applicable to the carrier or to which the carrier is entitled hereunder including the right to enforce any jurisdiction or arbitration provision contained herein shall also be available and shall extend to every such Servant of the carrier, who shall be entitled to enforce the same against the Merchant.",
    "(d)(i) The Merchant undertakes that no claim or allegation whether arising in contract, bailment, tort or otherwise shall be made against any Servant of the carrier which imposes or attempts to impose upon any of them or any vessel owned or chartered by any of them any liability whatsoever in connection with this contract whether or not arising out of negligence on the part of such Servant. The Servant shall also be entitled to enforce the foregoing covenant against the Merchant; and",
    "(ii) The Merchant undertakes that if any such claim or allegation should nevertheless be made, it will indemnify the carrier against all consequences thereof.",
    "For the purpose of sub-paragraphs (a)-(d) of this clause the Carrier is or shall be deemed to be acting as agent or trustee on behalf of and for the benefit of all persons mentioned in sub-clause (a) above who are its Servant and all such persons shall to this extent be or be deemed to be parties to this contract.",
    "19. Stowage.",
    "The Carrier shall have the right to stow cargo by means of containers, trailers, transportable tanks, flats, pallets, or similar articles of transport used to consolidate goods.",
    "The Carrier shall have the right to carry containers, trailers, transportable tanks and covered pallets, whether stowed by the Carrier or received by him in a stowed condition from the Merchant, on or under deck without notice to the Merchant.",
    "20. Shipper-Packed pallets.",
    "(a) The Merchant shall be liable to the Carrrier for any loss of or damage to its contents and shall cover any loss or expense incurred by the Carrier, if such loss, damage or expense has been caused by:",
    "negligent filling, packing or stowing of the Pallet;",
    "the contents being unsuitable for carriage in Pallet; or",
    "(iii) the unsuitability or defective condition of the Pallet unless the Pallet has been supplied by the Carrier and the unsuitability or defective condition would not have been apparent upon reasonable inspection at or prior to the time when the container was filled, packed or stowed.",
    "The Merchant shall indemnify the Carrier against any expenses, liabilities, losses, damages, claims or demands which the Carrier may incur or suffer by reason of any failure to comply with any relevant laws, regulations, directions or notices of Customs, port and any other authorities, or by reason of any infestation, contamination or condemnation of Goods and/or Pallets, insofar as such failure, infestation, contamination or condemnation arises from any act, neglect or default of the Merchant, the consignors or consignees of their Goods and/or Pallets, or their servants, agents or Sub-contractors.",
    "21. Return of Pallets.",
    "Pallets or similar articles of transport supplied by or on behalf of the Carrier shall be returned to the Carrier in the same order and condition as handed over to the Merchant, normal wear and tear excepted, with interiors clean and within the time prescribed in the Carrier's tariff or elsewhere.",
    "The Merchant shall be liable to the Carrier for any loss, damage to, or delay, including demurrage and detention incurred by or sustained to containers, pallets or similar articles of transport during the period between handing over to the Merchant and return to the Carrier.",
    "22. ANEMOS",
    "(a) The carrying-vessel shall be a vessel whose main propulsion is  wind power.",
    "(b) The Carrier shall offer to the Merchant ANEMOS Scheme, which is a collective trademark (class 39, APPENDICE XXX) that certifies a product has been shipped on board a wind powered vessel.",
    "(c)ANEMOS provides a tracking solution of the Vessel(s) and the Goods, and covers engine utilisation, CO2 emissions, CO2 emissions per unit of goods transported, as well as photographs, films, and all other contents which document the passage.",
    "(d) ANEMOS is materialized by a label applied onto each sail-transported product, which provides a visual differentiation to the end customer. The purpose of ANEMOS is to protect both the end customer (from greenwashing) and the cargo-Owners (from greenwashing competitors) in their commitment to reduce the carbon footprint of their maritime logistics, in full transparency and integrity.",
    "(e)The Carrier largely encourages the Merchant to certify their sail cargo crossings with ANEMOS, and to cooperate with other non-competing cargo-Owners in promoting and defending the ANEMOS label.",
    "ADDITIONAL CLAUSE",
    "U.S. Trade. Period of Responsibility.",
    "In case the Contract evidenced by this Bill of Lading is subject to the Carriage of Goods by Sea Act of the United States of America, 1936 (U.S. COGSA), then the provisions stated in said Act shall govern throughout the entire time the cargo is in the Carrier's custody and in which event freight shall be payable on the cargo coming into the Carrier's custody.",
    "If the U.S. COGSA applies, and unless the nature and value of the cargo has been declared by the shipper before the cargo has been handed over to the Carrier and inserted in this Bill of Lading, the Carrier shall in no event be or become liable for any loss or damage to the cargo in an amount exceeding USD 500 per package or customary freight unit.",
)
